<!doctype html>
<html lang="en">
<head>
   <meta charset="utf-8">
   <title><?= $this->title; ?></title>
   <meta name="viewport" content="width=device-width,initial-scale=1.0">
   <link href="/css/bootstrap.min.css" rel="stylesheet">
   <link href="/css/strapped.css" rel="stylesheet">
   <link rel="stylesheet" href="/css/bb.css">
</head>
<body>

<nav class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">
   <div class="container">
      <div class="navbar-header">
         <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
         </button>
         <a class="navbar-brand nav-link" href="/"><span>&lt;</span>th<span>&gt;</span></a>
      </div>

      <div class="collapse navbar-collapse navbar-ex1-collapse">
         <ul class="nav navbar-nav navbar-right">
            <li>
               <a href="/" class="nav-link">
                   <span class="btn">Docs</span>
               </a>
            </li>
             <li>
               <a href="/download.php" class="nav-link">
                   <span class="btn btn-success">Download</span>
               </a>
            </li>
         </ul>
      </div>
   </div>
</nav>

<?= $this->renderView(); ?>

<footer>
   <div class="container clearfix">
      <p class="pull-left">
         Copyright &copy; 2014 <a href="http://www.rodrigo-silveira.com">Rodrigo Silveira</a>. All rights reserved.
      </p>

      <p class="pull-right">&nbsp; &nbsp;<span>&lt;/</span>th<span>&gt;</span></p>
   </div>
</footer

<script src="/js/jquery.js"></script>
<script src="/js/bootstrap.min.js"></script>
<script>
   $(".nav-link").click(function(e) {
      e.preventDefault();
      var link = $(this);
      var href = link.attr("href");
      $("html,body").animate({scrollTop: $(href).offset().top - 80}, 500);
      link.closest(".navbar").find(".navbar-toggle:not(.collapsed)").click();
   });
</script>
</body>
</html>

</body>
</html>